
// Generated by SpritePad, Subchrist Software 2022.
// Assemble with 64TASS or similar.


// Colour values...

COLR_VIC_SCREEN = 0
COLR_VIC_SPRITE_MC1 = 14
COLR_VIC_SPRITE_MC2 = 1


// Quantities and dimensions...

SPRITE_COUNT = 1


// Data block sizes (in bytes)...

SZ_SPRITESET_DATA = 64
SZ_SPRITESET_ATTRIB_DATA = 1


// Data block addresses (dummy values)...

addr_spriteset_data = $1000
addr_spriteset_attrib_data = $1000




// * INSERT EXAMPLE PROGRAM HERE! * (or just include this file in your project).




// SpriteSet Data...
// 1 images, 64 bytes per image, total size is 64 ($40) bytes.

* = addr_spriteset_data
spriteset_data

sprite_image_0
.byte $00,$00,$00,$00,$00,$00,$00,$3C,$00,$00,$FF,$00,$00,$FF,$00,$03
.byte $FF,$C0,$03,$D7,$C0,$0F,$5A,$F0,$0F,$4E,$F0,$0F,$42,$F0,$0F,$42
.byte $F0,$0F,$AA,$F0,$0F,$EB,$F0,$03,$FF,$C0,$03,$FF,$C0,$00,$FF,$00
.byte $00,$3C,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$86



// SpriteSet Attribute Data...
// 1 attributes, 1 per image, 8 bits each, total size is 1 ($1) bytes.
// nb. Upper nybbles = MYXV, lower nybbles = colour (0-15).

* = addr_spriteset_attrib_data
spriteset_attrib_data

.byte $86



